apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cert-manager (required by KServe webhooks)
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml

  # Knative Serving + Kourier networking layer
  - https://github.com/knative/serving/releases/download/knative-v1.14.0/serving-core.yaml
  - https://github.com/knative-extensions/net-kourier/releases/download/knative-v1.14.0/kourier.yaml

  # KServe
  - https://github.com/kserve/kserve/releases/download/v0.12.1/kserve.yaml

patches:
  - path: patches/inferenceservice-config-ingress.yaml
  - path: patches/remove-inferenceservice-crd.yaml

